added reorganization to settings page
RyanBirtch-aot/common-hosted-form-service pull request #25
Opened 2024-09-24 22:24 UTC by RyanBirtch-aot

# Description

## Types of changes

## Checklist

- [ ] I have read the [CONTRIBUTING](/bcgov/common-hosted-form-service/blob/main/CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have run the npm script lint on the frontend and backend
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have approval from the product owner for the contribution in this pull request

## Further comments

2024-09-26 19:14 UTC, abhilash-aot requested changes

2024-09-26 19:14 UTC, abhilash-aot commented on components/src/components/Map/editForm/Component.edit.data.ts
> +          label: 'Add a point marker (drop a pin)',
rebase to feat-map branch as there is the polygon change added as well

2024-09-27 16:02 UTC, RyanBirtch-aot commented on components/src/components/Map/editForm/Component.edit.data.ts
> +          label: 'Add a point marker (drop a pin)',
rebased

2024-09-27 16:08 UTC, abhilash-aot approved these changes

2024-09-27 18:02 UTC, merged